# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development:
  adapter: postgresql
  encoding: unicode
  database: runyans_development
  pool: 5
  username: root
  password: root

test:
  adapter: postgresql
  encoding: unicode
  database: runyans_test
  pool: 5
  username: root
  password: root
